/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Certification {
  'name' : string,
  'year' : bigint,
  'issuer' : string,
}
export interface Content {
  'projects' : Array<Project>,
  'education' : Array<EducationEntry>,
  'heroText' : string,
  'experience' : Array<ExperienceItem>,
  'certifications' : Array<Certification>,
  'skills' : Array<string>,
  'hobbies' : Array<string>,
}
export interface EducationEntry {
  'institution' : string,
  'year' : bigint,
  'degree' : string,
}
export interface ExperienceItem {
  'duration' : string,
  'description' : string,
  'company' : string,
  'position' : string,
}
export interface Project {
  'title' : string,
  'link' : string,
  'description' : string,
  'details' : string,
}
export interface RecruiterVisit {
  'timestamp' : Time,
  'companyName' : [] | [string],
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VisitorMessage {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearRecruiterVisits' : ActorMethod<[string], undefined>,
  'clearVisitorMessages' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContent' : ActorMethod<[], Content>,
  'getRecruiterVisits' : ActorMethod<[string], Array<RecruiterVisit>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVisitorMessages' : ActorMethod<[string], Array<VisitorMessage>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logRecruiterVisit' : ActorMethod<[boolean, [] | [string]], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitVisitorMessage' : ActorMethod<[string, string, string], undefined>,
  'updateContent' : ActorMethod<[Content, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];