/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ContactDetails = IDL.Record({
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const Project = IDL.Record({
  'title' : IDL.Text,
  'link' : IDL.Text,
  'description' : IDL.Text,
  'details' : IDL.Text,
});
export const EducationEntry = IDL.Record({
  'institution' : IDL.Text,
  'year' : IDL.Nat,
  'degree' : IDL.Text,
});
export const ExperienceItem = IDL.Record({
  'duration' : IDL.Text,
  'description' : IDL.Text,
  'company' : IDL.Text,
  'position' : IDL.Text,
});
export const Certification = IDL.Record({
  'name' : IDL.Text,
  'year' : IDL.Nat,
  'issuer' : IDL.Text,
});
export const Content = IDL.Record({
  'contact' : ContactDetails,
  'projects' : IDL.Vec(Project),
  'education' : IDL.Vec(EducationEntry),
  'heroText' : IDL.Text,
  'experience' : IDL.Vec(ExperienceItem),
  'certifications' : IDL.Vec(Certification),
  'hobbies' : IDL.Vec(IDL.Text),
});
export const Time = IDL.Int;
export const RecruiterVisit = IDL.Record({
  'timestamp' : Time,
  'companyName' : IDL.Opt(IDL.Text),
});
export const VisitorMessage = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addSkillWithPassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearRecruiterVisitsWithPassword' : IDL.Func([IDL.Text], [], []),
  'clearSkillsWithPassword' : IDL.Func([IDL.Text], [], []),
  'clearVisitorMessagesWithPassword' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContent' : IDL.Func([], [Content], ['query']),
  'getRecruiterVisitsWithPassword' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(RecruiterVisit)],
      ['query'],
    ),
  'getSkills' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVisitorMessagesWithPassword' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(VisitorMessage)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logRecruiterVisit' : IDL.Func([IDL.Bool, IDL.Opt(IDL.Text)], [], []),
  'removeSkillWithPassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitVisitorMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateContentWithPassword' : IDL.Func([IDL.Text, Content], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ContactDetails = IDL.Record({
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Project = IDL.Record({
    'title' : IDL.Text,
    'link' : IDL.Text,
    'description' : IDL.Text,
    'details' : IDL.Text,
  });
  const EducationEntry = IDL.Record({
    'institution' : IDL.Text,
    'year' : IDL.Nat,
    'degree' : IDL.Text,
  });
  const ExperienceItem = IDL.Record({
    'duration' : IDL.Text,
    'description' : IDL.Text,
    'company' : IDL.Text,
    'position' : IDL.Text,
  });
  const Certification = IDL.Record({
    'name' : IDL.Text,
    'year' : IDL.Nat,
    'issuer' : IDL.Text,
  });
  const Content = IDL.Record({
    'contact' : ContactDetails,
    'projects' : IDL.Vec(Project),
    'education' : IDL.Vec(EducationEntry),
    'heroText' : IDL.Text,
    'experience' : IDL.Vec(ExperienceItem),
    'certifications' : IDL.Vec(Certification),
    'hobbies' : IDL.Vec(IDL.Text),
  });
  const Time = IDL.Int;
  const RecruiterVisit = IDL.Record({
    'timestamp' : Time,
    'companyName' : IDL.Opt(IDL.Text),
  });
  const VisitorMessage = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addSkillWithPassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearRecruiterVisitsWithPassword' : IDL.Func([IDL.Text], [], []),
    'clearSkillsWithPassword' : IDL.Func([IDL.Text], [], []),
    'clearVisitorMessagesWithPassword' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContent' : IDL.Func([], [Content], ['query']),
    'getRecruiterVisitsWithPassword' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(RecruiterVisit)],
        ['query'],
      ),
    'getSkills' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVisitorMessagesWithPassword' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(VisitorMessage)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logRecruiterVisit' : IDL.Func([IDL.Bool, IDL.Opt(IDL.Text)], [], []),
    'removeSkillWithPassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitVisitorMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateContentWithPassword' : IDL.Func([IDL.Text, Content], [], []),
  });
};

export const init = ({ IDL }) => { return []; };